// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddToWishlistTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addToWishlist() {
    driver.get("https://www.amazon.ca/");
    driver.manage().window().setSize(new Dimension(1512, 874));
    driver.findElement(By.linkText("Gift Ideas")).click();
    driver.findElement(By.cssSelector(".gs1jqp-0:nth-child(5) .rsqc7f-0")).click();
    driver.findElement(By.cssSelector("*[data-test=\"subcategory:kid8-neutral:books\"]")).click();
    js.executeScript("window.scrollTo(0,195)");
    driver.findElement(By.cssSelector("#gcx-gf-section-0 .d4xojt-0:nth-child(5) .b5zgse-0:nth-child(1) > .sc-167fkr-0:nth-child(1)")).click();
    driver.findElement(By.id("add-to-wishlist-button-submit")).click();
    driver.findElement(By.linkText("View your List")).click();
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#itemInfo_I1HKG1U3RO6ZZF > .a-row"));
      assert(elements.size() > 0);
    }
  }
}
